import type {Metadata} from "next";
import {SessionProvider} from "next-auth/react";
import ToasterProvider from "./providers/ToasterProvider";
import "./globals.css";
import NavBar from "@/app/navbar/NavBar";


export const metadata: Metadata = {
    title: "Carsties",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <SessionProvider> <ToasterProvider/> <NavBar/>
                    <main className="container mx-auto px-5 pt-10">
                        {/*<SignalRProvider>*/} {/*    {children}*/} {/*</SignalRProvider>*/} {children}
                    </main>
                </SessionProvider>
            </body>
        </html>
    );
}
