apiVersion: v1
kind: ConfigMap
metadata:
  name: auction-svc-config
data:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  ASPNETCORE_HTTP_PORTS: 8080F
  REDIS_HOST: auction.cache
  REDIS_PORT: "6379"
  ASPNETCORE_URLS: http://+:8080
  ConnectionStrings__DefaultConnection: "Host=postgres-clusterip;Database=auctions;Port=5432;Username=postgres;Password=postgres;Include Error Detail=true"
  ConnectionStrings__Redis: "redis-clusterip:6379"
  RabbitMq__Host: rabbitmq-clusterip
  RabbitMq__Port: "5672"
  RabbitMq__Username: guest
  RabbitMq__Password: guest
  Jwt__Key: your-super-secret-key-at-least-32-characters-long
  Jwt__Issuer: https://app.carsties.local
  Jwt__Audience: https://app.carsties.local
  Jwt__ExpireHours: "350"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
data:
  MONGO_INITDB_ROOT_USERNAME: root
  MONGO_INITDB_ROOT_PASSWORD: mongo
  MONGO_INITDB_DATABASE: searchdb

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: search-svc-config
data:
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_HTTP_PORTS: "8080"
  ConnectionStrings__MongoDb: "mongodb://root:mongo@mongo-clusterip:27017/searchdb?authSource=admin"
  RabbitMq__Host: rabbitmq-clusterip
  RabbitMq__Port: "5672"
  RabbitMq__Username: guest
  RabbitMq__Password: guest
  Jwt__Issuer: https://app.carsties.local
  Jwt__Audience: https://app.carsties.local

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bids-svc-config
data:
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_HTTP_PORTS: "8080"
  ConnectionStrings__BidDb: "mongodb://root:mongo@mongo-clusterip:27017/biddb?authSource=admin"
  Jwt__Issuer: https://app.carsties.local
  Jwt__Audience: https://app.carsties.local

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: identity-config
data:
  ASPNETCORE_ENVIRONMENT: Development
  ConnectionStrings__DefaultConnection: "Host=postgres-clusterip;Database=identity;Port=5432;Username=postgres;Password=postgres;Include Error Detail=true"
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  Jwt__Issuer: https://app.carsties.local
  Jwt__Audience: https://app.carsties.local

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-config
data:
  RabbitMQ__Host: rabbitmq-clusterip
