<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="FluentValidation" Version="12.0.0" />
      <PackageReference Include="Mapster" Version="7.4.2-pre02" />
      <PackageReference Include="MassTransit.EntityFrameworkCore" Version="8.5.3-develop.2365" />
      <PackageReference Include="MassTransit.RabbitMQ" Version="8.5.3-develop.2365" />
      <PackageReference Include="MediatR" Version="13.0.0" />
      <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.9" />
      <PackageReference Include="Polly" Version="8.6.3" />
      <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.4" />
      <PackageReference Include="Yarp.ReverseProxy" Version="2.3.0" />
    </ItemGroup>

</Project>
