events {
    worker_connections 1024;
    use epoll;
    multi_accept on;
}

http {
    upstream backend {
        server webapp:3000;
        # server backend2.example.com:3000;
        # server backend3.example.com:3000;
    }
    server {
        listen 80;
        location / {
            proxy_pass http://backend;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            add_header X-Backend-Instance $upstream_http_x_backend_instance always;
        }
        location /uploads/ {
            alias /usr/share/nginx/uploads/;
            autoindex on;
        }
       
    }
}