<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>disable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\Shared\Shared\Shared.csproj" />
      <ProjectReference Include="..\Auction.Application\Auction.Application.csproj" />
      <ProjectReference Include="..\Auction.infrastructure\Auction.infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Mapster" Version="7.4.2-pre02" />
      <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.9" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.9">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="9.0.9" />
      <PackageReference Include="Serilog" Version="4.3.0" />
      <PackageReference Include="Serilog.AspNetCore" Version="8.0.3" />
      <PackageReference Include="Serilog.Extensions.Hosting" Version="8.0.0" />
      <PackageReference Include="Serilog.Extensions.Logging" Version="9.0.2" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\..\..\..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

</Project>
